# Generated by Django 4.1.4 on 2023-01-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qtd_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='qtd_following',
            field=models.IntegerField(default=0),
        ),
    ]
