# Generated by Django 4.1.4 on 2023-01-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_biography_user_img_url_user_qtd_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
