# Generated by Django 4.1.4 on 2023-01-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_banner',
            field=models.URLField(blank=True),
        ),
    ]
