# Generated by Django 4.1.4 on 2023-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_img_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_config',
            field=models.IntegerField(default=0),
        ),
    ]
