# Generated by Django 4.1.4 on 2023-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_posts_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
