# Generated by Django 4.1.4 on 2023-02-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_user_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
